name: .NET

on:
  pull_request:
    branches: [ master ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release
    - name: Compress
      run: tar -czf release.tar.gz -C /home/runner/work/cards/cards/cards/bin/Release/net6.0/publish .
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{github.event.number}}
        files: release.tar.gz
    
